### PR TITLE
fix disabled keyboard input during active focus ring

### LINKED ISSUE #9: key events not accepted after setting the shortcut
Probably going to fix this myself, but to track the problem until then, here's what I mean:

- click inside a `RecordView`: it obtains key view status and shows a focus ring
- enter any shortcut: it shows the shortcut and the modifiers properly
- try to enter another shortcut

I expected the shortcut to be overwritten, especially since the focus ring is still drawn.

But instead I hear `NSBeep` and the value remains the same until I click inside the view again.

---

The issue is in [`RecordView.endRecording()`](https://github.com/Clipy/KeyHolder/blob/master/Lib/KeyHolder/RecordView.swift#L374):

     if window?.firstResponder == self && !canBecomeKeyView { window?.makeFirstResponder(nil) }

This properly emits an end editing event, but I think it should set the first responder back to `self` afterwards to remain consistent with the visual appearance (i.e. the focus ring that is still there).

### PR DESCRIPTION
**Pull request by DivineDominion**
This PR changes `beginRecording`/`endRecording` significantly: instead of starting/stopping the process, they are now mere callbacks of the `recording` property being changed. This unifies the information flow; previous to this PR, you could set `recording = true` without `beginRecording` being used to set up the modifiers, resulting in a weird state.

Also fixes #9.

### CODE REVIEW

**Comment by DivineDominion** [comment]
This lies around for a while now. What do you think about the fix?

**Comment by DivineDominion** [comment]
I rebased the branch on the current master for compatibility.

**Comment by DivineDominion** [comment]
@Econa77 I updated this PR's fixes to the current master as well

**Comment by DivineDominion** [comment]
@Econa77 Bugging you just to see if we could merge :)

**Comment by Econa77** [comment]
@DivineDominion I'm sorry I haven't been able to review it. The reason for not changing isRecoding directly is that you have to check the focus beforehand with `delegate?.recordViewShouldBeginRecording`.
I didn't intend to be able to change isRecoding, so I fixed it in #43.

There were too many differences from the current one, so some of the changes were addressed in #47.
Thank you so much for the Suggestions 🙏

**Pull request closed without merging**
